# Generated by Django 3.2.25 on 2024-11-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id_admin', models.AutoField(primary_key=True, serialize=False)),
                ('nom_admin', models.CharField(max_length=20)),
                ('ape_admin', models.CharField(max_length=40)),
                ('dir_admin', models.CharField(max_length=60)),
                ('correo_admin', models.CharField(max_length=30)),
                ('tel_admin', models.IntegerField()),
                ('user_admin', models.IntegerField()),
                ('pwd_admin', models.IntegerField()),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Carritocompra',
            fields=[
                ('id_carritocompras', models.AutoField(db_column='id_carritoCompras', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'carritocompra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'categorias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'facturas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_productos', models.AutoField(primary_key=True, serialize=False)),
                ('nom_producto', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=400)),
                ('precio', models.FloatField()),
                ('calificacion', models.IntegerField()),
                ('estado', models.CharField(max_length=6)),
                ('descuento', models.IntegerField()),
                ('fecha_pub', models.DateField()),
                ('imagen', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'productos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nom_usuario', models.CharField(max_length=20)),
                ('ape_usuario', models.CharField(max_length=40)),
                ('dir_usuario', models.CharField(max_length=60)),
                ('correo_usuario', models.CharField(max_length=20)),
                ('tel_usuario', models.IntegerField()),
                ('user_usuario', models.CharField(max_length=21)),
                ('pwd_usuario', models.CharField(max_length=21)),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
